---
# Common labels
- name: bug
  description: Something isn't working.
  color: B60205 # Red
- name: WIP
  description: This pull request is in Work In Progress state.
  color: ff7700 # Orange
- name: enhancement
  description: New feature or request
  color: 5319E7 # Purple

# Scope labels
- name: scope/ci
  description: Improvements or additions to CI.
  color: ffffff # White
- name: scope/backend
  description: Improvements or additions to backend.
  color: ffffff # White
- name: scope/frontend
  description: Improvements or additions to frontend.
  color: ffffff # White

# Languages labels
- name: javascript
  color: FBCA04 # Yellow
- name: golang
  color: 0075ca # Blue
- name: markdown 
  color: 4d332c # Brown
- name: yaml
  color: 4d332c # Brown

# Sizing labels
- name: size/XS
  description: Denotes a PR that changes 0-9 lines.
  color: 009900
- name: size/S
  description: Denotes a PR that changes 10-29 lines.
  color: 77bb00
- name: size/M
  description: Denotes a PR that changes 30-99 lines.
  color: eebb00
- name: size/L
  description: Denotes a PR that changes 100-499 lines.
  color: ee9900
- name: size/XL
  description: Denotes a PR that changes 500-999 lines.
  color: ee5500
- name: size/XXL
  description: Denotes a PR that changes 1000+ lines.
  color: ee0000
